# Generated by Django 2.2.7 on 2019-11-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='avr_score',
        ),
    ]
